### ISSUE TITLE
Enable Edit and Delete User

### ISSUE THREAD

**Issue by dedenbangkit** [akvo/rtmis#157]
Backend:
- [x] Change order of User list to descending, coalesce updated or created. Please also test the order.
- [x] User detail endpoint.
   GET `/user/{:id}/`:
   ```jsx
   {
    first_name: "string",
    last_name: "string",
    email: "user@example.com",
    administration: 0,
    role: 1,
    phone_number: "string",
    designation: "string",
    forms: [{
        id: 124234,
        name: "test form"
    }],
    pending_approval: int, /* total */
    data: int, /* total */
   }
   ```
   If role changes from Admin / Approver to User and user has assigned to pending data approval then return `422 Unprocessable Entity`
- [x] User Delete Endpoint:
      DELETE `/user/{:id}/`

Frontend:
- [x] Designation and Phone is not showing in the expanded Data
- [ ] [Edit User Layout](https://xd.adobe.com/view/26c48557-3a9c-40c6-a370-f4af7991c47a-7397/screen/bdd84f0d-c5f9-4b2d-95eb-fd56666e2be7/)
- [ ] Delete User with:
  - [Alert 1](https://xd.adobe.com/view/26c48557-3a9c-40c6-a370-f4af7991c47a-7397/screen/12bb409b-a905-47d2-82f0-5ff91ee9439e/)
  - [Alert 2](https://xd.adobe.com/view/26c48557-3a9c-40c6-a370-f4af7991c47a-7397/screen/26ac6933-2cc9-446e-876a-2dbc82a39ec6/)

**Comment by nirav9spl** [comment]
@dedenbangkit We are only storing created date in user model, updated date is not there, Do you want me add that ?

**Comment by dedenbangkit** [comment]
Yes @nirav9spl, we should add updated and created
