### ISSUE TITLE
Expand Batch Data Details in Approval Page

### ISSUE THREAD

**Issue by dedenbangkit** [akvo/rtmis#270]

**Comment by dedenbangkit** [comment]
![Screen Shot 2022-04-19 at 08 45 18](https://user-images.githubusercontent.com/3245109/163904127-c819ba62-e444-48b5-af4e-f0f144ed2df6.png)

Expandable data is blank

**Comment by mantiz8x** [comment]
> ![Screen Shot 2022-04-19 at 08 45 18](https://user-images.githubusercontent.com/3245109/163904127-c819ba62-e444-48b5-af4e-f0f144ed2df6.png)
> 
> Expandable data is blank

This can be fixed by adding question id to the rows returned in http://localhost:3000/api/doc/#/Pending%20Data/v1_batch_summary_list in the backend. Currently the keys question, type, and value are returned.
