### ISSUE TITLE
Add a read only role

### ISSUE THREAD

**Issue by joycarpediem** [akvo/rtmis#305]
- [ ] Name it  "Institutional User"
- [ ] They can only view the dashboards
- [ ] they will not have access to control center 
- [ ] They will only have access to the region that is defined in their profile
- [ ] Administrators can add them to their county or lower levels
- [ ] Super admins can add them to national or lower levels 
- [ ] Add an Inline paragraph to show the details of the roles, under role dropdown field

**Comment by dedenbangkit** [comment]
@abhishek-p-s please extend the [role](https://github.com/akvo/rtmis/blob/93ea3ff729bdf8ae09bc7873a65d4b71facc5a4b/frontend/src/lib/config.js#L4) in the config.js

I will add role id 5 for the new role
