### ISSUE TITLE
Remove Logo from Footer

### ISSUE THREAD

**Issue by kevinmugambi** [akvo/rtmis#411]
As per Govt of Kenya guidelines, we cannot have two "coat of arms" (Govt Logo) on the same page. MoH ICT suggested we remove the one on the footer.

![Untitled](https://user-images.githubusercontent.com/97939672/170261081-3388a4bb-501f-4365-b6b0-2b72d245284d.png)

**Comment by wayangalihpratama** [comment]
Requested to reassigned to @mantiz8x
