### ISSUE TITLE
For number questions 0 should be considered as a valid value

### ISSUE THREAD

**Issue by joycarpediem** [akvo/rtmis#501]

**Comment by dedenbangkit** [comment]
@wayangalihpratama Please follow this answer:

https://github.com/ant-design/ant-design/issues/18806#issuecomment-810186992

and check if we can replace [TypeNumber.jsx](https://github.com/akvo/akvo-react-form/blob/main/src/fields/TypeNumber.jsx#L36) without any deprecation

**Comment by wayangalihpratama** [comment]
- Solved on [akvo-react-form-#45](https://github.com/akvo/akvo-react-form/issues/45) ( v1.6.1 )

**Comment by dedenbangkit** [comment]
![Screen Shot 2022-06-28 at 12 11 18](https://user-images.githubusercontent.com/3245109/176097792-aa4b6750-a385-4080-ab05-e3f04a45d32b.png)

this 0 Value should also be affecting the question group and progress @wayangalihpratama

**Comment by wayangalihpratama** [comment]
- Solved on this update [akvo-react-form#45](https://github.com/akvo/akvo-react-form/commit/5e900ee5032127ecc69b9e402f31a3eafc9ecfbc) ( v1.6.2 )
