### ISSUE TITLE
administration column not visible when downloading spreadsheet for visual table 

### ISSUE THREAD

**Issue by joycarpediem** [akvo/rtmis#606]
Columns are part of the spreadsheet but width seems to be 0

**Comment by dedenbangkit** [comment]
It works @joycarpediem. But when you preview them with Mac spreadsheet preview (press space in the finder) the column does not show. You should open them with Open Office / Ms. Excel.
![Screen Shot 2022-07-26 at 04 44 01](https://user-images.githubusercontent.com/3245109/180879141-94949aa8-db2f-46bf-bcd2-43a2cb1d34b9.png)
