### ISSUE TITLE
Ordering of question groups is messed up

### ISSUE THREAD

**Issue by joycarpediem** [akvo/rtmis#608]
<img width="1247" alt="Screenshot 2022-07-25 at 10 58 11 PM" src="https://user-images.githubusercontent.com/4419787/180872964-a35310b2-f4ad-4ad2-8e7e-4c5610a841aa.png">

**Comment by dedenbangkit** [comment]
It's only happening in rtmis.akvotest.org, staging is ok @joycarpediem. But I'll check them

**Comment by dedenbangkit** [comment]
![Screen Shot 2022-07-26 at 04 33 57](https://user-images.githubusercontent.com/3245109/180877877-beb58af6-1194-4cb1-8943-054d9b533337.png)
