### ISSUE TITLE
Add reports

### ISSUE THREAD

**Issue by joycarpediem** [akvo/rtmis#619]
Same design as dashboards
Add a menu item next to the dashboards
Will have the same list
On clicking the page will be displayed with the filter 

They will just contain the tables that we currently have under dashboard
We will remove the tables from the dashboard

**Comment by wayangalihpratama** [comment]
- [ ] Add a menu item next to the dashboards, on clicking the page will be displayed with the filter 
- [ ] Report page config contain the tables that we currently have under dashboard
- [ ] Remove the tables from the dashboard config
