### ISSUE TITLE
Handling the "No Approver" situation

### ISSUE THREAD

**Issue by joycarpediem** [akvo/rtmis#626]
@dedenbangkit , i was think that we can put a couple of checks to stop this from happening . This is in addition to #624 
* We should put a check that a submitter/approver can only  be added to the system for questionnaire where there is atleast one approver/county admin above them ( for county questionnaires)
* When someone tries to batch data or upload data , there should be a check before the batch is created ( or data upload accepted) , that there are approvers in the chain for this data . It will depend on how the code is and whether we can already find out the approval chain for the data 

Let me know your thoughts on this topic and then we can decide on a plan of action

**Comment by kevinmugambi** [comment]
Another suggestion here was county admins must get notified when data has no approvers.

**Comment by wayangalihpratama** [comment]
- [ ] Create API to check approver for selected form & user administration
- [ ] Implement API call when click "Batch Selected Data" button
- [ ] Implement API call when click select form on "Bulk Upload" data
- [ ] Show notification if there's no approver
