### ISSUE TITLE
First Time User Setup on Project Setup

### ISSUE THREAD

**Issue by karimkkanji** [akvo/rtmis#706]
After setting up the project via docker for development, [the documentation](https://github.com/akvo/rtmis/blob/main/README.md) does not explicitly indicate how to set up a first time user, that is the super user.

Tried Setting up a user via  ``` python manage.py createsuperuser``` but does not work. 

Adding this to documentation will make it easier to contribute to the repository.

**Comment by dedenbangkit** [comment]
Hi @karimkkanji an update has been made to the README file. Thanks to remind the absence of these instructions.

**Comment by karimkkanji** [comment]
Thanks @dedenbangkit for the quick update. Tested and works excellent. Closing this issue.
